import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import {
  InputTier,
  KeepStatus,
  RuleOperator,
  SymptomItemType,
  SymptomRole,
  UrgencyMode,
} from "../src/generated/prisma/enums.ts";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

const normalizeText = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, " ")
    .trim();

const symptoms = [
  {
    code: "G001",
    name: "Demam",
    normalizedName: normalizeText("Demam"),
    questionText: "Apakah anak mengalami demam?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G002",
    name: "Demam tinggi akut",
    normalizedName: normalizeText("Demam tinggi akut"),
    questionText: "Apakah anak mengalami demam tinggi yang muncul akut?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G003",
    name: "Batuk",
    normalizedName: normalizeText("Batuk"),
    questionText: "Apakah anak mengalami batuk?",
    category: "respiratory",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G004",
    name: "Pilek",
    normalizedName: normalizeText("Pilek"),
    questionText: "Apakah anak mengalami pilek atau hidung berair?",
    category: "respiratory",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G005",
    name: "Sakit tenggorokan",
    normalizedName: normalizeText("Sakit tenggorokan"),
    questionText: "Apakah anak mengalami sakit tenggorokan?",
    category: "respiratory",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G006",
    name: "Sakit kepala",
    normalizedName: normalizeText("Sakit kepala"),
    questionText: "Apakah anak mengalami sakit kepala?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G007",
    name: "Nyeri otot",
    normalizedName: normalizeText("Nyeri otot"),
    questionText: "Apakah anak mengalami nyeri otot?",
    category: "musculoskeletal",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G008",
    name: "Nyeri sendi",
    normalizedName: normalizeText("Nyeri sendi"),
    questionText: "Apakah anak mengalami nyeri sendi?",
    category: "musculoskeletal",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G009",
    name: "Nyeri belakang mata",
    normalizedName: normalizeText("Nyeri belakang mata"),
    questionText: "Apakah anak mengalami nyeri di belakang mata?",
    category: "eye",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G010",
    name: "Ruam",
    normalizedName: normalizeText("Ruam"),
    questionText: "Apakah anak mengalami ruam pada kulit?",
    category: "skin",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G011",
    name: "Mual",
    normalizedName: normalizeText("Mual"),
    questionText: "Apakah anak mengalami mual?",
    category: "digestive",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G012",
    name: "Muntah",
    normalizedName: normalizeText("Muntah"),
    questionText: "Apakah anak mengalami muntah?",
    category: "digestive",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G013",
    name: "Muntah persisten",
    normalizedName: normalizeText("Muntah persisten"),
    questionText: "Apakah anak mengalami muntah terus-menerus?",
    category: "digestive",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G014",
    name: "Nyeri perut",
    normalizedName: normalizeText("Nyeri perut"),
    questionText: "Apakah anak mengalami nyeri perut?",
    category: "digestive",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G015",
    name: "Perdarahan mukosa",
    normalizedName: normalizeText("Perdarahan mukosa"),
    questionText: "Apakah anak mengalami perdarahan dari mukosa, misalnya mulut atau hidung?",
    category: "bleeding",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G016",
    name: "Mimisan",
    normalizedName: normalizeText("Mimisan"),
    questionText: "Apakah anak mengalami mimisan?",
    category: "bleeding",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G017",
    name: "Gusi berdarah",
    normalizedName: normalizeText("Gusi berdarah"),
    questionText: "Apakah anak mengalami gusi berdarah?",
    category: "bleeding",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G018",
    name: "Mudah memar / bintik perdarahan",
    normalizedName: normalizeText("Mudah memar / bintik perdarahan"),
    questionText: "Apakah anak mudah memar atau muncul bintik perdarahan pada kulit?",
    category: "bleeding",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G019",
    name: "Letih berat / sangat lemas",
    normalizedName: normalizeText("Letih berat / sangat lemas"),
    questionText: "Apakah anak tampak sangat lemas, mengantuk terus, atau kurang responsif?",
    category: "general",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G020",
    name: "Gelisah",
    normalizedName: normalizeText("Gelisah"),
    questionText: "Apakah anak tampak sangat gelisah atau tidak tenang?",
    category: "general",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G021",
    name: "Sesak napas",
    normalizedName: normalizeText("Sesak napas"),
    questionText: "Apakah anak mengalami sesak napas atau tampak kesulitan bernapas?",
    category: "respiratory",
    itemType: SymptomItemType.SEVERITY,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G022",
    name: "Sulit bernapas",
    normalizedName: normalizeText("Sulit bernapas"),
    questionText: "Apakah anak tampak sulit bernapas?",
    category: "respiratory",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G023",
    name: "Napas cepat",
    normalizedName: normalizeText("Napas cepat"),
    questionText: "Apakah napas anak tampak lebih cepat dari biasanya?",
    category: "respiratory",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G024",
    name: "Tidak mau minum",
    normalizedName: normalizeText("Tidak mau minum"),
    questionText: "Apakah anak tidak mau minum atau asupan minumnya sangat berkurang?",
    category: "digestive",
    itemType: SymptomItemType.WARNING,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G025",
    name: "Diare",
    normalizedName: normalizeText("Diare"),
    questionText: "Apakah anak mengalami diare?",
    category: "digestive",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G026",
    name: "Nafsu makan menurun",
    normalizedName: normalizeText("Nafsu makan menurun"),
    questionText: "Apakah nafsu makan anak menurun?",
    category: "digestive",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G027",
    name: "Nyeri telinga",
    normalizedName: normalizeText("Nyeri telinga"),
    questionText: "Apakah anak mengeluh nyeri telinga?",
    category: "ear",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G028",
    name: "Telinga keluar cairan",
    normalizedName: normalizeText("Telinga keluar cairan"),
    questionText: "Apakah terdapat cairan yang keluar dari telinga anak?",
    category: "ear",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G029",
    name: "Demam tinggi 3-4 hari",
    normalizedName: normalizeText("Demam tinggi 3-4 hari"),
    questionText: "Apakah anak mengalami demam tinggi selama sekitar 3–4 hari?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G030",
    name: "Ruam muncul saat demam turun",
    normalizedName: normalizeText("Ruam muncul saat demam turun"),
    questionText: "Apakah ruam muncul saat demam anak mulai turun?",
    category: "skin",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G031",
    name: "Ruam mulai di badan / trunk",
    normalizedName: normalizeText("Ruam mulai di badan / trunk"),
    questionText: "Apakah ruam mulai muncul dari badan atau trunk?",
    category: "skin",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G032",
    name: "Kejang demam",
    normalizedName: normalizeText("Kejang demam"),
    questionText: "Apakah anak mengalami kejang saat atau setelah demam?",
    category: "neurologic",
    itemType: SymptomItemType.SEVERITY,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G033",
    name: "Gatal di sekitar anus",
    normalizedName: normalizeText("Gatal di sekitar anus"),
    questionText: "Apakah anak sering merasa gatal di sekitar anus?",
    category: "parasitic",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G034",
    name: "Gatal pada malam hari",
    normalizedName: normalizeText("Gatal pada malam hari"),
    questionText: "Apakah gatal di sekitar anus lebih sering muncul pada malam hari?",
    category: "parasitic",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G035",
    name: "Cacing terlihat di area anus / pakaian tidur",
    normalizedName: normalizeText("Cacing terlihat di area anus / pakaian tidur"),
    questionText: "Apakah terlihat cacing di sekitar anus atau pada pakaian tidur anak saat malam hari?",
    category: "parasitic",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G036",
    name: "Gangguan tidur",
    normalizedName: normalizeText("Gangguan tidur"),
    questionText: "Apakah anak mengalami gangguan tidur atau sulit tidur?",
    category: "behavior",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G037",
    name: "Iritabilitas / rewel",
    normalizedName: normalizeText("Iritabilitas / rewel"),
    questionText: "Apakah anak tampak lebih rewel atau mudah marah dari biasanya?",
    category: "behavior",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G038",
    name: "Sulit fokus",
    normalizedName: normalizeText("Sulit fokus"),
    questionText: "Apakah anak tampak sulit fokus atau perhatiannya mudah teralihkan?",
    category: "behavior",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G039",
    name: "Menggigil",
    normalizedName: normalizeText("Menggigil"),
    questionText: "Apakah anak mengalami menggigil?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G040",
    name: "Riwayat perjalanan ke area endemis malaria",
    normalizedName: normalizeText("Riwayat perjalanan ke area endemis malaria"),
    questionText: "Apakah anak memiliki riwayat perjalanan ke daerah endemis malaria?",
    category: "context",
    itemType: SymptomItemType.CONTEXT,
    defaultInputTier: InputTier.HISTORY_CONTEXT,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G041",
    name: "Kulit atau mata kuning",
    normalizedName: normalizeText("Kulit atau mata kuning"),
    questionText: "Apakah kulit atau mata anak tampak kuning?",
    category: "general",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G042",
    name: "Gatal area genital",
    normalizedName: normalizeText("Gatal area genital"),
    questionText: "Apakah anak mengalami gatal pada area genital?",
    category: "genitourinary",
    itemType: SymptomItemType.COMPLICATION,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G043",
    name: "Nyeri saat BAK",
    normalizedName: normalizeText("Nyeri saat BAK"),
    questionText: "Apakah anak mengalami nyeri saat buang air kecil?",
    category: "genitourinary",
    itemType: SymptomItemType.SYMPTOM,
    defaultInputTier: InputTier.CAREGIVER,
    isRedFlag: false,
    isAskable: true,
  },
  {
    code: "G044",
    name: "Gangguan kesadaran",
    normalizedName: normalizeText("Gangguan kesadaran"),
    questionText: "Apakah anak tampak bingung, sangat mengantuk, atau mengalami gangguan kesadaran?",
    category: "neurologic",
    itemType: SymptomItemType.SEVERITY,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G045",
    name: "Kejang",
    normalizedName: normalizeText("Kejang"),
    questionText: "Apakah anak mengalami kejang?",
    category: "neurologic",
    itemType: SymptomItemType.SEVERITY,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
  {
    code: "G046",
    name: "Syok / hipotensi",
    normalizedName: normalizeText("Syok / hipotensi"),
    questionText: "Apakah anak tampak sangat lemah, pucat, dingin, atau ada dugaan syok?",
    category: "circulation",
    itemType: SymptomItemType.SEVERITY,
    defaultInputTier: InputTier.CAREGIVER_OR_CLINICIAN,
    isRedFlag: true,
    isAskable: true,
  },
] as const;

const symptomAliases = [
  { aliasText: "gatal bokong", symptomCode: "G033" },
  { aliasText: "gatal anus", symptomCode: "G033" },
  { aliasText: "gatal perianal", symptomCode: "G033" },
  { aliasText: "gatal malam hari", symptomCode: "G034" },
  { aliasText: "cacing terlihat", symptomCode: "G035" },
  { aliasText: "nyeri di belakang mata", symptomCode: "G009" },
  { aliasText: "muntah-muntah", symptomCode: "G012" },
  { aliasText: "muntah terus-menerus", symptomCode: "G013" },
  { aliasText: "perut terasa sakit", symptomCode: "G014" },
  { aliasText: "sesak", symptomCode: "G021" },
  { aliasText: "sesak berat", symptomCode: "G021" },
  { aliasText: "napas cepat", symptomCode: "G023" },
  { aliasText: "mimisan", symptomCode: "G016" },
  { aliasText: "gusi berdarah", symptomCode: "G017" },
  { aliasText: "mudah memar", symptomCode: "G018" },
  { aliasText: "bintik perdarahan", symptomCode: "G018" },
  { aliasText: "tidak mau minum", symptomCode: "G024" },
  { aliasText: "pilek", symptomCode: "G004" },
  { aliasText: "nyeri telinga", symptomCode: "G027" },
  { aliasText: "cairan telinga", symptomCode: "G028" },
  { aliasText: "demam tinggi 3-4 hari", symptomCode: "G029" },
  { aliasText: "ruam setelah demam turun", symptomCode: "G030" },
  { aliasText: "ruam mulai di badan", symptomCode: "G031" },
  { aliasText: "riwayat perjalanan malaria", symptomCode: "G040" },
  { aliasText: "kulit kuning", symptomCode: "G041" },
  { aliasText: "mata kuning", symptomCode: "G041" },
] as const;

const diseases = [
  {
    code: "P001",
    name: "Threadworm / Enterobiasis",
    severityLevel: "medium",
    description: "Infeksi Enterobius vermicularis pada anak, khas dengan gatal di sekitar anus terutama malam hari dan dapat berulang.",
    advice: "Jaga kebersihan tangan, kuku, sprei, dan pakaian. Konsultasikan pengobatan seluruh anggota rumah bila perlu.",
    sourceUrl: "https://doi.org/10.1136/archdischild-2025-328497",
  },
  {
    code: "P003",
    name: "Influenza",
    severityLevel: "medium",
    description: "Infeksi influenza pada anak dengan gejala demam, batuk, pilek, sakit tenggorokan, nyeri otot, dan sakit kepala.",
    advice: "Istirahat cukup, cukupkan cairan, dan periksa bila anak sesak, sangat lemas, atau tidak mau minum.",
    sourceUrl: "https://doi.org/10.1542/pir.2023-005962",
  },
  {
    code: "P004",
    name: "Dengue / DBD",
    severityLevel: "critical",
    description: "Infeksi dengue pada anak yang dapat berkembang menjadi warning signs dan dengue berat.",
    advice: "Segera ke fasilitas kesehatan bila ada mimisan, gusi berdarah, muntah persisten, nyeri perut berat, atau anak tampak sangat lemas.",
    sourceUrl: "https://doi.org/10.1016/S0140-6736(23)02576-X",
  },
  {
    code: "P005",
    name: "Acute Gastroenteritis with Dehydration",
    severityLevel: "high",
    description: "Diare akut pada anak yang dapat disertai muntah dan menyebabkan dehidrasi.",
    advice: "Berikan cairan/oralit dan segera periksa bila anak tidak mau minum, muntah terus, atau tampak dehidrasi.",
    sourceUrl: "https://doi.org/10.1016/j.anpede.2021.04.011",
  },
  {
    code: "P006",
    name: "Pneumonia / CAP",
    severityLevel: "critical",
    description: "Infeksi paru pada anak yang dapat menyebabkan batuk, demam, napas cepat, dan sesak.",
    advice: "Segera ke fasilitas kesehatan bila anak bernapas cepat, sesak, atau tampak sangat lemas.",
    sourceUrl: "https://doi.org/10.3345/cep.2022.01452",
  },
  {
    code: "P010",
    name: "Roseola infantum",
    severityLevel: "medium",
    description: "Infeksi virus pada bayi/anak kecil yang khas dengan demam tinggi 3–4 hari lalu ruam saat demam turun.",
    advice: "Pantau suhu tubuh, cukupkan cairan, dan periksa bila anak kejang, sangat lemas, atau sulit minum.",
    sourceUrl: "https://doi.org/10.2174/1573396319666221118123844",
  },
  {
    code: "P013",
    name: "Acute Otitis Media (AOM)",
    severityLevel: "medium",
    description: "Infeksi telinga tengah yang dapat menimbulkan nyeri telinga, demam, dan kadang cairan dari telinga.",
    advice: "Periksakan ke dokter bila nyeri telinga berat, demam tinggi, atau cairan telinga terus keluar.",
    sourceUrl: "https://doi.org/10.1186/s13052-024-01588-y",
  },
  {
    code: "P014",
    name: "Malaria",
    severityLevel: "high",
    description: "Infeksi malaria yang dapat menimbulkan demam, menggigil, sakit kepala, nyeri otot, dan menjadi berat pada kasus tertentu.",
    advice: "Segera periksa ke fasilitas kesehatan, terutama bila ada riwayat perjalanan ke daerah endemis malaria.",
    sourceUrl: "https://doi.org/10.1016/j.clinme.2024.100258",
  },
] as const;

const rules = [
  {
    code: "R001",
    name: "Aturan Threadworm / Enterobiasis",
    diseaseCode: "P001",
    operator: RuleOperator.AND,
    minMatch: 2,
    priority: 10,
    symptoms: [
      { code: "G033", isMandatory: true },
      { code: "G034", isMandatory: false },
      { code: "G035", isMandatory: false },
      { code: "G036", isMandatory: false },
      { code: "G037", isMandatory: false },
      { code: "G038", isMandatory: false },
      { code: "G014", isMandatory: false },
      { code: "G026", isMandatory: false },
      { code: "G042", isMandatory: false },
      { code: "G043", isMandatory: false },
    ],
  },
  {
    code: "R003",
    name: "Aturan Influenza",
    diseaseCode: "P003",
    operator: RuleOperator.AND,
    minMatch: 3,
    priority: 8,
    symptoms: [
      { code: "G001", isMandatory: true },
      { code: "G003", isMandatory: true },
      { code: "G004", isMandatory: false },
      { code: "G005", isMandatory: false },
      { code: "G006", isMandatory: false },
      { code: "G007", isMandatory: false },
      { code: "G012", isMandatory: false },
      { code: "G025", isMandatory: false },
    ],
  },
  {
    code: "R004",
    name: "Aturan Dengue / DBD",
    diseaseCode: "P004",
    operator: RuleOperator.AND,
    minMatch: 4,
    priority: 12,
    symptoms: [
      { code: "G002", isMandatory: true },
      { code: "G006", isMandatory: false },
      { code: "G007", isMandatory: false },
      { code: "G008", isMandatory: false },
      { code: "G009", isMandatory: false },
      { code: "G010", isMandatory: false },
      { code: "G011", isMandatory: false },
      { code: "G012", isMandatory: false },
      { code: "G014", isMandatory: false },
      { code: "G016", isMandatory: false },
      { code: "G017", isMandatory: false },
      { code: "G018", isMandatory: false },
      { code: "G013", isMandatory: false },
      { code: "G019", isMandatory: false },
    ],
  },
  {
    code: "R005",
    name: "Aturan Acute Gastroenteritis with Dehydration",
    diseaseCode: "P005",
    operator: RuleOperator.AND,
    minMatch: 2,
    priority: 9,
    symptoms: [
      { code: "G025", isMandatory: true },
      { code: "G012", isMandatory: false },
      { code: "G011", isMandatory: false },
      { code: "G014", isMandatory: false },
      { code: "G024", isMandatory: false },
      { code: "G026", isMandatory: false },
    ],
  },
  {
    code: "R006",
    name: "Aturan Pneumonia / CAP",
    diseaseCode: "P006",
    operator: RuleOperator.AND,
    minMatch: 3,
    priority: 11,
    symptoms: [
      { code: "G003", isMandatory: true },
      { code: "G001", isMandatory: false },
      { code: "G021", isMandatory: false },
      { code: "G022", isMandatory: false },
      { code: "G023", isMandatory: false },
      { code: "G019", isMandatory: false },
    ],
  },
  {
    code: "R010",
    name: "Aturan Roseola infantum",
    diseaseCode: "P010",
    operator: RuleOperator.AND,
    minMatch: 2,
    priority: 10,
    symptoms: [
      { code: "G029", isMandatory: true },
      { code: "G030", isMandatory: true },
      { code: "G010", isMandatory: false },
      { code: "G031", isMandatory: false },
      { code: "G037", isMandatory: false },
      { code: "G032", isMandatory: false },
    ],
  },
  {
    code: "R013",
    name: "Aturan Acute Otitis Media (AOM)",
    diseaseCode: "P013",
    operator: RuleOperator.AND,
    minMatch: 2,
    priority: 8,
    symptoms: [
      { code: "G027", isMandatory: true },
      { code: "G028", isMandatory: false },
      { code: "G001", isMandatory: false },
      { code: "G037", isMandatory: false },
    ],
  },
  {
    code: "R014",
    name: "Aturan Malaria",
    diseaseCode: "P014",
    operator: RuleOperator.AND,
    minMatch: 3,
    priority: 11,
    symptoms: [
      { code: "G001", isMandatory: true },
      { code: "G039", isMandatory: false },
      { code: "G006", isMandatory: false },
      { code: "G007", isMandatory: false },
      { code: "G025", isMandatory: false },
      { code: "G040", isMandatory: false },
      { code: "G041", isMandatory: false },
    ],
  },
] as const;

const weights = [
  // P001 Threadworm
  { diseaseCode: "P001", symptomCode: "G033", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Primary symptom" },
  { diseaseCode: "P001", symptomCode: "G034", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Night pattern matters" },
  { diseaseCode: "P001", symptomCode: "G035", cfExpert: 0.95, candidateCfMin: 0.90, candidateCfMax: 1.00, symptomRole: SymptomRole.CORE, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Highly specific sign" },
  { diseaseCode: "P001", symptomCode: "G036", cfExpert: 0.55, candidateCfMin: 0.45, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Sleep disruption" },
  { diseaseCode: "P001", symptomCode: "G037", cfExpert: 0.45, candidateCfMin: 0.35, candidateCfMax: 0.50, symptomRole: SymptomRole.SUPPORTING, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Often linked to poor sleep" },
  { diseaseCode: "P001", symptomCode: "G038", cfExpert: 0.35, candidateCfMin: 0.25, candidateCfMax: 0.40, symptomRole: SymptomRole.SUPPORTING, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Low specificity" },
  { diseaseCode: "P001", symptomCode: "G014", cfExpert: 0.30, candidateCfMin: 0.20, candidateCfMax: 0.35, symptomRole: SymptomRole.SUPPORTING, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Sometimes reported" },
  { diseaseCode: "P001", symptomCode: "G026", cfExpert: 0.30, candidateCfMin: 0.20, candidateCfMax: 0.35, symptomRole: SymptomRole.SUPPORTING, phase: "active_infection", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Occasional" },
  { diseaseCode: "P001", symptomCode: "G042", cfExpert: 0.60, candidateCfMin: 0.50, candidateCfMax: 0.70, symptomRole: SymptomRole.COMPLICATION, phase: "extraintestinal", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Genital itching / vulvovaginitis" },
  { diseaseCode: "P001", symptomCode: "G043", cfExpert: 0.25, candidateCfMin: 0.20, candidateCfMax: 0.35, symptomRole: SymptomRole.SUPPORTING, phase: "extraintestinal", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1136/archdischild-2025-328497", note: "Dysuria can occur" },

  // P003 Influenza
  { diseaseCode: "P003", symptomCode: "G001", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G003", cfExpert: 0.85, candidateCfMin: 0.75, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G004", cfExpert: 0.70, candidateCfMin: 0.60, candidateCfMax: 0.75, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G005", cfExpert: 0.55, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G006", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G007", cfExpert: 0.55, candidateCfMin: 0.45, candidateCfMax: 0.65, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: null },
  { diseaseCode: "P003", symptomCode: "G012", cfExpert: 0.30, candidateCfMin: 0.25, candidateCfMax: 0.40, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: "GI symptoms can occur" },
  { diseaseCode: "P003", symptomCode: "G025", cfExpert: 0.25, candidateCfMin: 0.20, candidateCfMax: 0.35, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1542/pir.2023-005962", note: "GI symptoms can occur" },

  // P004 Dengue
  { diseaseCode: "P004", symptomCode: "G002", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G006", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G007", cfExpert: 0.55, candidateCfMin: 0.45, candidateCfMax: 0.65, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G008", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G009", cfExpert: 0.65, candidateCfMin: 0.55, candidateCfMax: 0.70, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G010", cfExpert: 0.45, candidateCfMin: 0.35, candidateCfMax: 0.55, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G011", cfExpert: 0.40, candidateCfMin: 0.35, candidateCfMax: 0.50, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G012", cfExpert: 0.50, candidateCfMin: 0.45, candidateCfMax: 0.60, symptomRole: SymptomRole.CORE, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: null },
  { diseaseCode: "P004", symptomCode: "G014", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.WARNING_SIGN, phase: "critical_preceding", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Abdominal pain warning sign" },
  { diseaseCode: "P004", symptomCode: "G016", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.90, symptomRole: SymptomRole.WARNING_SIGN, phase: "critical_preceding", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Mimisan" },
  { diseaseCode: "P004", symptomCode: "G017", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.90, symptomRole: SymptomRole.WARNING_SIGN, phase: "critical_preceding", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Gusi berdarah" },
  { diseaseCode: "P004", symptomCode: "G018", cfExpert: 0.70, candidateCfMin: 0.45, candidateCfMax: 0.65, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Minor bleeding" },
  { diseaseCode: "P004", symptomCode: "G013", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.WARNING_SIGN, phase: "critical_preceding", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Persistent vomiting" },
  { diseaseCode: "P004", symptomCode: "G019", cfExpert: 0.90, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.WARNING_SIGN, phase: "critical_preceding", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/S0140-6736(23)02576-X", note: "Lethargy" },

  // P005 AGE
  { diseaseCode: "P005", symptomCode: "G025", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },
  { diseaseCode: "P005", symptomCode: "G012", cfExpert: 0.70, candidateCfMin: 0.60, candidateCfMax: 0.80, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },
  { diseaseCode: "P005", symptomCode: "G011", cfExpert: 0.45, candidateCfMin: 0.35, candidateCfMax: 0.50, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },
  { diseaseCode: "P005", symptomCode: "G014", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },
  { diseaseCode: "P005", symptomCode: "G024", cfExpert: 0.90, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.WARNING_SIGN, phase: "dehydration", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },
  { diseaseCode: "P005", symptomCode: "G026", cfExpert: 0.55, candidateCfMin: 0.45, candidateCfMax: 0.65, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.anpede.2021.04.011", note: null },

  // P006 Pneumonia
  { diseaseCode: "P006", symptomCode: "G003", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.3345/cep.2022.01452", note: null },
  { diseaseCode: "P006", symptomCode: "G001", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.60, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.3345/cep.2022.01452", note: null },
  { diseaseCode: "P006", symptomCode: "G021", cfExpert: 0.95, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.SEVERE, phase: "severe", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.URGENCY_ONLY, evidenceDoi: "10.3345/cep.2022.01452", note: "Respiratory distress" },
  { diseaseCode: "P006", symptomCode: "G022", cfExpert: 0.85, candidateCfMin: 0.75, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.3345/cep.2022.01452", note: null },
  { diseaseCode: "P006", symptomCode: "G023", cfExpert: 0.90, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.3345/cep.2022.01452", note: null },
  { diseaseCode: "P006", symptomCode: "G019", cfExpert: 0.60, candidateCfMin: 0.50, candidateCfMax: 0.70, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.3345/cep.2022.01452", note: null },

  // P010 Roseola
  { diseaseCode: "P010", symptomCode: "G029", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.2174/1573396319666221118123844", note: null },
  { diseaseCode: "P010", symptomCode: "G030", cfExpert: 0.95, candidateCfMin: 0.90, candidateCfMax: 1.00, symptomRole: SymptomRole.CORE, phase: "defervescence", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.2174/1573396319666221118123844", note: "Signature pattern" },
  { diseaseCode: "P010", symptomCode: "G010", cfExpert: 0.80, candidateCfMin: 0.75, candidateCfMax: 0.90, symptomRole: SymptomRole.CORE, phase: "defervescence", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.2174/1573396319666221118123844", note: null },
  { diseaseCode: "P010", symptomCode: "G031", cfExpert: 0.65, candidateCfMin: 0.55, candidateCfMax: 0.70, symptomRole: SymptomRole.SUPPORTING, phase: "defervescence", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.2174/1573396319666221118123844", note: "Starts on trunk" },
  { diseaseCode: "P010", symptomCode: "G037", cfExpert: 0.35, candidateCfMin: 0.25, candidateCfMax: 0.40, symptomRole: SymptomRole.SUPPORTING, phase: "febrile", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.2174/1573396319666221118123844", note: "Irritability can occur" },
  { diseaseCode: "P010", symptomCode: "G032", cfExpert: 0.90, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.SEVERE, phase: "febrile", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.URGENCY_ONLY, evidenceDoi: "10.2174/1573396319666221118123844", note: "Febrile seizure" },

  // P013 AOM
  { diseaseCode: "P013", symptomCode: "G027", cfExpert: 0.85, candidateCfMin: 0.80, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1186/s13052-024-01588-y", note: null },
  { diseaseCode: "P013", symptomCode: "G028", cfExpert: 0.75, candidateCfMin: 0.70, candidateCfMax: 0.90, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1186/s13052-024-01588-y", note: null },
  { diseaseCode: "P013", symptomCode: "G001", cfExpert: 0.40, candidateCfMin: 0.30, candidateCfMax: 0.50, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1186/s13052-024-01588-y", note: null },
  { diseaseCode: "P013", symptomCode: "G037", cfExpert: 0.30, candidateCfMin: 0.25, candidateCfMax: 0.40, symptomRole: SymptomRole.SUPPORTING, phase: "acute", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1186/s13052-024-01588-y", note: "Infants can be nonspecific" },

  // P014 Malaria
  { diseaseCode: "P014", symptomCode: "G001", cfExpert: 0.90, candidateCfMin: 0.85, candidateCfMax: 0.95, symptomRole: SymptomRole.CORE, phase: "acute_presentation", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: null },
  { diseaseCode: "P014", symptomCode: "G039", cfExpert: 0.70, candidateCfMin: 0.60, candidateCfMax: 0.75, symptomRole: SymptomRole.CORE, phase: "acute_presentation", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: null },
  { diseaseCode: "P014", symptomCode: "G006", cfExpert: 0.60, candidateCfMin: 0.50, candidateCfMax: 0.65, symptomRole: SymptomRole.SUPPORTING, phase: "acute_presentation", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: null },
  { diseaseCode: "P014", symptomCode: "G007", cfExpert: 0.50, candidateCfMin: 0.40, candidateCfMax: 0.55, symptomRole: SymptomRole.SUPPORTING, phase: "acute_presentation", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: null },
  { diseaseCode: "P014", symptomCode: "G025", cfExpert: 0.35, candidateCfMin: 0.25, candidateCfMax: 0.40, symptomRole: SymptomRole.SUPPORTING, phase: "acute_presentation", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: "Diarrhoea can occur in children" },
  { diseaseCode: "P014", symptomCode: "G040", cfExpert: 0.90, candidateCfMin: null, candidateCfMax: null, symptomRole: SymptomRole.CONTEXT_ONLY, phase: "exposure_context", keepStatus: KeepStatus.KEEP, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: "Essential travel context" },
  { diseaseCode: "P014", symptomCode: "G041", cfExpert: 0.45, candidateCfMin: 0.35, candidateCfMax: 0.50, symptomRole: SymptomRole.SUPPORTING, phase: "acute_presentation", keepStatus: KeepStatus.KEEP_OPTIONAL, urgencyMode: UrgencyMode.ORDINARY, evidenceDoi: "10.1016/j.clinme.2024.100258", note: "Can contribute to misdiagnosis" },
] as const;

async function main() {
  await prisma.consultationResult.deleteMany();
  await prisma.consultationAnswer.deleteMany();
  await prisma.consultation.deleteMany();
  await prisma.ruleDetail.deleteMany();
  await prisma.rule.deleteMany();
  await prisma.diseaseSymptomWeight.deleteMany();
  await prisma.symptomAlias.deleteMany();
  await prisma.symptom.deleteMany();
  await prisma.disease.deleteMany();

  for (const symptom of symptoms) {
    await prisma.symptom.create({
      data: symptom,
    });
  }

  const symptomMap = new Map(
    (await prisma.symptom.findMany()).map((symptom) => [symptom.code, symptom.id]),
  );

  for (const alias of symptomAliases) {
    const symptomId = symptomMap.get(alias.symptomCode);
    if (!symptomId) continue;

    await prisma.symptomAlias.create({
      data: {
        symptomId,
        aliasText: alias.aliasText,
        normalizedAlias: normalizeText(alias.aliasText),
      },
    });
  }

  for (const disease of diseases) {
    await prisma.disease.create({
      data: disease,
    });
  }

  const diseaseMap = new Map(
    (await prisma.disease.findMany()).map((disease) => [disease.code, disease.id]),
  );

  for (const rule of rules) {
    const createdRule = await prisma.rule.create({
      data: {
        code: rule.code,
        name: rule.name,
        diseaseId: diseaseMap.get(rule.diseaseCode)!,
        operator: rule.operator,
        minMatch: rule.minMatch,
        priority: rule.priority,
      },
    });

    for (const item of rule.symptoms) {
      await prisma.ruleDetail.create({
        data: {
          ruleId: createdRule.id,
          symptomId: symptomMap.get(item.code)!,
          isMandatory: item.isMandatory,
        },
      });
    }
  }

  for (const weight of weights) {
    await prisma.diseaseSymptomWeight.create({
      data: {
        diseaseId: diseaseMap.get(weight.diseaseCode)!,
        symptomId: symptomMap.get(weight.symptomCode)!,
        cfExpert: weight.cfExpert,
        candidateCfMin: weight.candidateCfMin,
        candidateCfMax: weight.candidateCfMax,
        symptomRole: weight.symptomRole,
        phase: weight.phase,
        keepStatus: weight.keepStatus,
        urgencyMode: weight.urgencyMode,
        evidenceDoi: weight.evidenceDoi,
        note: weight.note,
      },
    });
  }

  console.log("Seed final V2 selesai: schema baru + dataset tervalidasi berhasil ditambahkan.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
