export type ScenarioCategory =
  | "typical"
  | "overlap"
  | "red_flag"
  | "edge_case"
  | "out_of_context";

export type DiagnosisScenario = {
  scenarioId: string;
  category: ScenarioCategory;
  description: string;
  childName: string;
  childAgeMonths: number;
  gender: "MALE" | "FEMALE";
  answers: {
    symptomCode: string;
    userCf: number;
  }[];
  targetDiseaseCode: string | null;
  targetDiseaseName: string | null;
  expectedTop1?: string | null;
  expectedTop3Includes?: string[];
  expectedUrgencyLevel?: "LOW" | "MEDIUM" | "HIGH" | "EMERGENCY";
  expectedResultStatus:
    | "EXPECTED_TOP1"
    | "EXPECTED_TOP3"
    | "EXPECTED_NO_DIAGNOSIS"
    | "EXPECTED_RED_FLAG"
    | "OUT_OF_CONTEXT";
};

const defaultProfile = {
  childName: "Anak Evaluasi",
  childAgeMonths: 60,
  gender: "FEMALE" as const,
};

export const diagnosisScenarios: DiagnosisScenario[] = [
  {
    scenarioId: "S01",
    category: "typical",
    description: "Typical Measles dengan demam tinggi, batuk kering, mata berair, ruam, dan Koplik spots.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G002", userCf: 1 },
      { symptomCode: "G004", userCf: 0.8 },
      { symptomCode: "G005", userCf: 0.8 },
      { symptomCode: "G006", userCf: 1 },
      { symptomCode: "G007", userCf: 0.8 },
      { symptomCode: "G003", userCf: 0.6 },
    ],
    targetDiseaseCode: "P001",
    targetDiseaseName: "Measles / Campak",
    expectedTop1: "P001",
    expectedTop3Includes: ["P001"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S02",
    category: "typical",
    description: "Typical Malaria dengan demam, sakit kepala, muntah, menggigil, berkeringat, dan nafsu makan turun.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G014", userCf: 1 },
      { symptomCode: "G015", userCf: 0.8 },
      { symptomCode: "G013", userCf: 0.6 },
      { symptomCode: "G003", userCf: 0.6 },
    ],
    targetDiseaseCode: "P002",
    targetDiseaseName: "Malaria",
    expectedTop1: "P002",
    expectedTop3Includes: ["P002"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S03",
    category: "typical",
    description: "Typical Typhoid fever dengan demam, sakit kepala, sakit perut, diare, nafsu makan turun, dan mudah lelah.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G009", userCf: 0.8 },
      { symptomCode: "G017", userCf: 0.6 },
      { symptomCode: "G003", userCf: 1 },
      { symptomCode: "G020", userCf: 0.8 },
    ],
    targetDiseaseCode: "P003",
    targetDiseaseName: "Typhoid fever / Demam tifoid",
    expectedTop1: "P003",
    expectedTop3Includes: ["P003"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S04",
    category: "typical",
    description: "Typical Diarrhea dengan sering BAB, BAB cair, kram perut, mual, kembung, dan nafsu makan turun.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G024", userCf: 1 },
      { symptomCode: "G025", userCf: 1 },
      { symptomCode: "G027", userCf: 0.8 },
      { symptomCode: "G023", userCf: 0.6 },
      { symptomCode: "G022", userCf: 0.6 },
      { symptomCode: "G003", userCf: 0.6 },
    ],
    targetDiseaseCode: "P004",
    targetDiseaseName: "Diarrhea / Diare",
    expectedTop1: "P004",
    expectedTop3Includes: ["P004"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S05",
    category: "typical",
    description: "Typical ISPA dengan demam, batuk, bersin, hidung tersumbat/berair, mata merah, dan suara serak.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G031", userCf: 0.8 },
      { symptomCode: "G032", userCf: 0.8 },
      { symptomCode: "G030", userCf: 0.8 },
      { symptomCode: "G033", userCf: 0.8 },
    ],
    targetDiseaseCode: "P005",
    targetDiseaseName: "Acute Respiratory Infection / ISPA",
    expectedTop1: "P005",
    expectedTop3Includes: ["P005"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S06",
    category: "typical",
    description: "Typical DBD dengan demam, sakit kepala, mual, muntah, ruam, dan perdarahan ringan.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G034", userCf: 0.8 },
      { symptomCode: "G013", userCf: 0.8 },
      { symptomCode: "G006", userCf: 0.8 },
      { symptomCode: "G036", userCf: 1 },
    ],
    targetDiseaseCode: "P006",
    targetDiseaseName: "Dengue Hemorrhagic Fever / DBD",
    expectedTop1: "P006",
    expectedTop3Includes: ["P006"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S07",
    category: "typical",
    description: "Typical Pneumonia dengan demam, batuk, suara napas tidak normal, sesak napas, dan nyeri dada.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G037", userCf: 0.8 },
      { symptomCode: "G038", userCf: 1 },
      { symptomCode: "G039", userCf: 0.8 },
    ],
    targetDiseaseCode: "P007",
    targetDiseaseName: "Pneumonia",
    expectedTop1: "P007",
    expectedTop3Includes: ["P007"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S08",
    category: "typical",
    description: "Typical Varicella dengan demam, sakit kepala, sakit tenggorokan, nafsu makan turun, bintik merah, dan vesikel.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.6 },
      { symptomCode: "G008", userCf: 0.6 },
      { symptomCode: "G018", userCf: 0.4 },
      { symptomCode: "G003", userCf: 0.4 },
      { symptomCode: "G019", userCf: 0.8 },
      { symptomCode: "G041", userCf: 1 },
    ],
    targetDiseaseCode: "P008",
    targetDiseaseName: "Varicella / Cacar air",
    expectedTop1: "P008",
    expectedTop3Includes: ["P008"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S09",
    category: "typical",
    description: "Measles tanpa Koplik spots, tetapi ada demam tinggi, batuk kering, mata berair, dan ruam.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G002", userCf: 0.8 },
      { symptomCode: "G004", userCf: 0.8 },
      { symptomCode: "G005", userCf: 0.8 },
      { symptomCode: "G006", userCf: 0.8 },
    ],
    targetDiseaseCode: "P001",
    targetDiseaseName: "Measles / Campak",
    expectedTop1: "P001",
    expectedTop3Includes: ["P001"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S10",
    category: "typical",
    description: "Pneumonia dengan batuk, demam, lesu, sesak napas, dan nafsu makan menurun.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G021", userCf: 0.8 },
      { symptomCode: "G038", userCf: 0.8 },
      { symptomCode: "G003", userCf: 0.6 },
    ],
    targetDiseaseCode: "P007",
    targetDiseaseName: "Pneumonia",
    expectedTop1: "P007",
    expectedTop3Includes: ["P007"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_TOP1",
  },

  {
    scenarioId: "S11",
    category: "overlap",
    description: "Overlap ISPA dan Pneumonia, dominan ISPA karena gejala pernapasan atas lengkap.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G032", userCf: 0.8 },
      { symptomCode: "G033", userCf: 0.8 },
      { symptomCode: "G031", userCf: 0.8 },
    ],
    targetDiseaseCode: "P005",
    targetDiseaseName: "Acute Respiratory Infection / ISPA",
    expectedTop1: "P005",
    expectedTop3Includes: ["P005", "P007"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S12",
    category: "overlap",
    description: "Overlap DBD dan Malaria, dominan DBD karena ruam, mual, muntah, dan demam.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G013", userCf: 0.8 },
      { symptomCode: "G034", userCf: 0.8 },
      { symptomCode: "G006", userCf: 0.8 },
    ],
    targetDiseaseCode: "P006",
    targetDiseaseName: "Dengue Hemorrhagic Fever / DBD",
    expectedTop1: "P006",
    expectedTop3Includes: ["P006", "P002"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S13",
    category: "overlap",
    description: "Overlap Typhoid dan Diarrhea, dominan Typhoid karena demam, sakit kepala, sakit perut, mudah lelah, dan nafsu makan turun.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G009", userCf: 0.8 },
      { symptomCode: "G017", userCf: 0.6 },
      { symptomCode: "G003", userCf: 0.8 },
      { symptomCode: "G020", userCf: 0.6 },
    ],
    targetDiseaseCode: "P003",
    targetDiseaseName: "Typhoid fever / Demam tifoid",
    expectedTop1: "P003",
    expectedTop3Includes: ["P003", "P004"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S14",
    category: "overlap",
    description: "Overlap Varicella dan Measles, dominan Varicella karena vesikel cairan bening.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.6 },
      { symptomCode: "G003", userCf: 0.4 },
      { symptomCode: "G019", userCf: 0.8 },
      { symptomCode: "G041", userCf: 1 },
      { symptomCode: "G018", userCf: 0.4 },
    ],
    targetDiseaseCode: "P008",
    targetDiseaseName: "Varicella / Cacar air",
    expectedTop1: "P008",
    expectedTop3Includes: ["P008"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S15",
    category: "overlap",
    description: "Overlap Measles dan DBD karena ruam dan demam, dominan Measles karena mata berair dan batuk kering.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G002", userCf: 0.8 },
      { symptomCode: "G006", userCf: 0.8 },
      { symptomCode: "G005", userCf: 0.8 },
      { symptomCode: "G004", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.4 },
    ],
    targetDiseaseCode: "P001",
    targetDiseaseName: "Measles / Campak",
    expectedTop1: "P001",
    expectedTop3Includes: ["P001", "P006"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S16",
    category: "overlap",
    description: "Overlap Pneumonia dan ISPA, dominan Pneumonia karena napas cepat dan sesak napas.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G032", userCf: 0.6 },
      { symptomCode: "G011", userCf: 0.8 },
      { symptomCode: "G038", userCf: 1 },
    ],
    targetDiseaseCode: "P007",
    targetDiseaseName: "Pneumonia",
    expectedTop1: "P007",
    expectedTop3Includes: ["P007", "P005"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S17",
    category: "overlap",
    description: "Overlap Malaria dan Typhoid, dominan Malaria karena menggigil dan berkeringat banyak.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G009", userCf: 0.6 },
      { symptomCode: "G013", userCf: 0.6 },
      { symptomCode: "G014", userCf: 1 },
      { symptomCode: "G015", userCf: 1 },
    ],
    targetDiseaseCode: "P002",
    targetDiseaseName: "Malaria",
    expectedTop1: "P002",
    expectedTop3Includes: ["P002", "P003"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S18",
    category: "overlap",
    description: "Overlap Diarrhea dan Typhoid, dominan Diarrhea karena sering BAB, BAB cair, dan kram perut.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G017", userCf: 0.8 },
      { symptomCode: "G024", userCf: 1 },
      { symptomCode: "G025", userCf: 1 },
      { symptomCode: "G027", userCf: 0.8 },
      { symptomCode: "G003", userCf: 0.6 },
    ],
    targetDiseaseCode: "P004",
    targetDiseaseName: "Diarrhea / Diare",
    expectedTop1: "P004",
    expectedTop3Includes: ["P004", "P003"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },

  {
    scenarioId: "S19",
    category: "red_flag",
    description: "Pneumonia emergency dengan batuk, sesak napas, dan suara napas tidak normal.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G028", userCf: 0.8 },
      { symptomCode: "G038", userCf: 1 },
      { symptomCode: "G037", userCf: 1 },
    ],
    targetDiseaseCode: "P007",
    targetDiseaseName: "Pneumonia",
    expectedTop1: "P007",
    expectedTop3Includes: ["P007"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },
  {
    scenarioId: "S20",
    category: "red_flag",
    description: "DBD emergency dengan perdarahan ringan dan gelisah.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G036", userCf: 1 },
      { symptomCode: "G013", userCf: 0.8 },
      { symptomCode: "G035", userCf: 0.8 },
    ],
    targetDiseaseCode: "P006",
    targetDiseaseName: "Dengue Hemorrhagic Fever / DBD",
    expectedTop1: "P006",
    expectedTop3Includes: ["P006"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },
  {
    scenarioId: "S21",
    category: "red_flag",
    description: "Diare emergency dengan tanda dehidrasi berat.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G024", userCf: 1 },
      { symptomCode: "G025", userCf: 1 },
      { symptomCode: "G021", userCf: 0.8 },
      { symptomCode: "G044", userCf: 1 },
    ],
    targetDiseaseCode: "P004",
    targetDiseaseName: "Diarrhea / Diare",
    expectedTop1: "P004",
    expectedTop3Includes: ["P004"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },
  {
    scenarioId: "S22",
    category: "red_flag",
    description: "Typhoid high urgency dengan halusinasi dan demam tinggi berkepanjangan.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G009", userCf: 0.8 },
      { symptomCode: "G016", userCf: 1 },
      { symptomCode: "G045", userCf: 1 },
    ],
    targetDiseaseCode: "P003",
    targetDiseaseName: "Typhoid fever / Demam tifoid",
    expectedTop1: "P003",
    expectedTop3Includes: ["P003"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },
  {
    scenarioId: "S23",
    category: "red_flag",
    description: "Malaria high urgency dengan napas cepat dan sangat lemah.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G014", userCf: 1 },
      { symptomCode: "G015", userCf: 1 },
      { symptomCode: "G011", userCf: 0.8 },
      { symptomCode: "G046", userCf: 1 },
    ],
    targetDiseaseCode: "P002",
    targetDiseaseName: "Malaria",
    expectedTop1: "P002",
    expectedTop3Includes: ["P002"],
    expectedUrgencyLevel: "HIGH",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },
  {
    scenarioId: "S24",
    category: "red_flag",
    description: "DBD emergency dengan kejang.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G001", userCf: 0.8 },
      { symptomCode: "G008", userCf: 0.8 },
      { symptomCode: "G006", userCf: 0.8 },
      { symptomCode: "G042", userCf: 1 },
    ],
    targetDiseaseCode: "P006",
    targetDiseaseName: "Dengue Hemorrhagic Fever / DBD",
    expectedTop1: "P006",
    expectedTop3Includes: ["P006"],
    expectedUrgencyLevel: "EMERGENCY",
    expectedResultStatus: "EXPECTED_RED_FLAG",
  },

  {
    scenarioId: "S25",
    category: "edge_case",
    description: "Edge case demam saja, sistem seharusnya tidak menghasilkan diagnosis kuat.",
    ...defaultProfile,
    answers: [{ symptomCode: "G001", userCf: 0.8 }],
    targetDiseaseCode: null,
    targetDiseaseName: null,
    expectedTop1: null,
    expectedTop3Includes: [],
    expectedUrgencyLevel: "LOW",
    expectedResultStatus: "EXPECTED_NO_DIAGNOSIS",
  },
  {
    scenarioId: "S26",
    category: "edge_case",
    description: "Minimal Varicella dengan bintik merah dan vesikel cairan bening.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G019", userCf: 0.8 },
      { symptomCode: "G041", userCf: 1 },
    ],
    targetDiseaseCode: "P008",
    targetDiseaseName: "Varicella / Cacar air",
    expectedTop1: "P008",
    expectedTop3Includes: ["P008"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },
  {
    scenarioId: "S27",
    category: "edge_case",
    description: "Minimal Diarrhea dengan sering BAB dan BAB cair.",
    ...defaultProfile,
    answers: [
      { symptomCode: "G024", userCf: 0.8 },
      { symptomCode: "G025", userCf: 0.8 },
    ],
    targetDiseaseCode: "P004",
    targetDiseaseName: "Diarrhea / Diare",
    expectedTop1: "P004",
    expectedTop3Includes: ["P004"],
    expectedUrgencyLevel: "MEDIUM",
    expectedResultStatus: "EXPECTED_TOP1",
  },

  {
    scenarioId: "S28",
    category: "out_of_context",
    description: "Out-of-context: laptop rusak.",
    ...defaultProfile,
    answers: [],
    targetDiseaseCode: null,
    targetDiseaseName: null,
    expectedTop1: null,
    expectedTop3Includes: [],
    expectedUrgencyLevel: "LOW",
    expectedResultStatus: "OUT_OF_CONTEXT",
  },
  {
    scenarioId: "S29",
    category: "out_of_context",
    description: "Out-of-context: orang dewasa sakit gigi.",
    ...defaultProfile,
    answers: [],
    targetDiseaseCode: null,
    targetDiseaseName: null,
    expectedTop1: null,
    expectedTop3Includes: [],
    expectedUrgencyLevel: "LOW",
    expectedResultStatus: "OUT_OF_CONTEXT",
  },
  {
    scenarioId: "S30",
    category: "out_of_context",
    description: "Out-of-context: pertanyaan membuat website.",
    ...defaultProfile,
    answers: [],
    targetDiseaseCode: null,
    targetDiseaseName: null,
    expectedTop1: null,
    expectedTop3Includes: [],
    expectedUrgencyLevel: "LOW",
    expectedResultStatus: "OUT_OF_CONTEXT",
  },
];